# Generated by Django 5.2 on 2026-06-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach_name',
            field=models.CharField(default='Unknown Coach', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('PITCHER', 'Pitcher'), ('CATCHER', 'Catcher'), ('FIRST BASE', 'First Base'), ('SECOND BASE', 'Second Base'), ('THIRD BASE', 'Third Base'), ('SHORTSTOP', 'Shortstop'), ('LEFT FIELD', 'Left Field'), ('CENTER FIELD', 'Center Field'), ('RIGHT FIELD', 'Right Field')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'number')},
        ),
    ]
